Travel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainApp.views import *
from usersApp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('users/', include('usersApp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class TurUser(AbstractUser):
    USER_TYPES = [
        ('sayohatchi', 'Sayohatchi'),
        ('taxi_egasi', 'Taxi park egasi'),
        ('gid', 'Gid (yo‘lboschi)'),
        ('mehmonxona_egasi', 'Mehmonxona egasi'),
    ]

    user_type = models.CharField(max_length=30, choices=USER_TYPES, verbose_name="Foydalanuvchi turi")
    phone = models.CharField(max_length=20, verbose_name="Telefon raqam", blank=True, null=True)
    country = models.CharField(max_length=100, verbose_name="Davlat", blank=True, null=True)
    city = models.CharField(max_length=100, verbose_name="Shahar", blank=True, null=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True, verbose_name="Profil rasmi")
    description = models.TextField(blank=True, null=True, verbose_name="Qo‘shimcha ma’lumot")

    def __str__(self):
        return f"{self.username} — {self.get_user_type_display()}"

    class Meta:
        verbose_name = "TurUser"
        verbose_name_plural = "TurUser"

templates/about.html
{% extends 'base.html' %}
     {% block content %}

        <!-- About Start -->
        <div class="container-fluid about py-5">
            <div class="container py-5">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-5">
                        <div class="h-100" style="border: 50px solid; border-color: transparent #13357B transparent #13357B;">
                            <img src="img/about-img.jpg" class="img-fluid w-100 h-100" alt="">
                        </div>
                    </div>
                    <div class="col-lg-7" style="background: linear-gradient(rgba(255, 255, 255, .8), rgba(255, 255, 255, .8)), url(img/about-img-1.png);">
                        <h5 class="section-about-title pe-3">About Us</h5>
                        <h1 class="mb-4">Welcome to <span class="text-primary">Travela</span></h1>
                        <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, dolorum, doloribus sunt dicta, officia voluptatibus libero necessitatibus natus impedit quam ullam assumenda? Id atque iste consectetur. Commodi odit ab saepe!</p>
                        <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium quos voluptatem suscipit neque enim, doloribus ipsum rem eos distinctio, dignissimos nisi saepe nulla? Libero numquam perferendis provident placeat molestiae quia?</p>
                        <div class="row gy-2 gx-4 mb-4">
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>First Class Flights</p>
                            </div>
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Handpicked Hotels</p>
                            </div>
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>5 Star Accommodations</p>
                            </div>
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>Latest Model Vehicles</p>
                            </div>
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>150 Premium City Tours</p>
                            </div>
                            <div class="col-sm-6">
                                <p class="mb-0"><i class="fa fa-arrow-right text-primary me-2"></i>24/7 Service</p>
                            </div>
                        </div>
                        <a class="btn btn-primary rounded-pill py-3 px-5 mt-2" href="">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->

        <!-- Travel Guide Start -->
        <div class="container-fluid guide py-5">
            <div class="container py-5">
                <div class="mx-auto text-center mb-5" style="max-width: 900px;">
                    <h5 class="section-title px-3">Travel Guide</h5>
                    <h1 class="mb-0">Meet Our Guide</h1>
                </div>
                <div class="row g-4">
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="img/guide-1.jpg" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="img/guide-2.jpg" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="img/guide-3.jpg" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3">
                        <div class="guide-item">
                            <div class="guide-img">
                                <div class="guide-img-efects">
                                    <img src="img/guide-4.jpg" class="img-fluid w-100 rounded-top" alt="Image">
                                </div>
                                <div class="guide-icon rounded-pill p-2">
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-instagram"></i></a>
                                    <a class="btn btn-square btn-primary rounded-circle mx-1" href=""><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="guide-title text-center rounded-bottom p-4">
                                <div class="guide-title-inner">
                                    <h4 class="mt-3">Full Name</h4>
                                    <p class="mb-0">Designation</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Travel Guide End -->

        <!-- Subscribe Start -->
        <div class="container-fluid subscribe py-5">
            <div class="container text-center py-5">
                <div class="mx-auto text-center" style="max-width: 900px;">
                    <h5 class="subscribe-title px-3">Subscribe</h5>
                    <h1 class="text-white mb-4">Our Newsletter</h1>
                    <p class="text-white mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum tempore nam, architecto doloremque velit explicabo? Voluptate sunt eveniet fuga eligendi! Expedita laudantium fugiat corrupti eum cum repellat a laborum quasi.
                    </p>
                    <div class="position-relative mx-auto">
                        <input class="form-control border-primary rounded-pill w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary rounded-pill position-absolute top-0 end-0 py-2 px-4 mt-2 me-2">Subscribe</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Subscribe End -->
{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kirish</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),
                        url("{% static 'img/bg-tour.jpg' %}") center/cover no-repeat;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .login-card {
            background: rgba(255, 255, 255, 0.97);
            border-radius: 15px;
            box-shadow: 0 0 25px rgba(0,0,0,0.4);
            padding: 40px;
            width: 100%;
            max-width: 400px;
        }
        .form-control {
            border-radius: 10px;
            padding: 10px 12px;
            margin-bottom: 15px;
        }
        .btn-primary {
            width: 100%;
            border-radius: 10px;
            font-weight: 600;
        }
        h2 {
            text-align: center;
            color: #0d6efd;
            margin-bottom: 25px;
        }
        .error {
            color: red;
            font-size: 14px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="login-card">
        <h2><i class="fa fa-sign-in-alt"></i> Tizimga kirish</h2>

        <form method="post">
            {% csrf_token %}
            <label for="username">Foydalanuvchi nomi</label>
            <input type="text" name="username" id="username" class="form-control" required>

            <label for="password">Parol</label>
            <input type="password" name="password" id="password" class="form-control" required>

            <button type="submit" class="btn btn-primary">
                <i class="fa fa-sign-in-alt me-1"></i> Kirish
            </button>

            <div class="text-center mt-3">
                <small>Hali akkauntingiz yo‘qmi?
                    <a href="{% url 'register' %}" class="text-primary fw-bold">Ro‘yxatdan o‘tish</a>
                </small>
            </div>
        </form>
    </div>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ro‘yxatdan o‘tish</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),
                        url("{% static 'img/bg-tour.jpg' %}") center/cover no-repeat;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .register-card {
            background: rgba(255, 255, 255, 0.97);
            border-radius: 15px;
            box-shadow: 0 0 25px rgba(0,0,0,0.4);
            padding: 40px;
            width: 100%;
            max-width: 500px;
        }
        .form-control, .form-select, textarea {
            border-radius: 10px;
            padding: 10px 12px;
            margin-bottom: 15px;
        }
        .btn-primary {
            width: 100%;
            border-radius: 10px;
            font-weight: 600;
        }
        h2 {
            text-align: center;
            color: #0d6efd;
            margin-bottom: 25px;
        }
        label {
            font-weight: 500;
        }
        .error {
            color: red;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="register-card">
        <h2><i class="fa fa-user-plus"></i> Ro‘yxatdan o‘tish</h2>

        <form method="post" enctype="multipart/form-data" id="registerForm">
            {% csrf_token %}

            <label for="id_username">Foydalanuvchi nomi</label>
            <input type="text" id="id_username" name="username" class="form-control" required>

            <label for="id_email">Email</label>
            <input type="email" id="id_email" name="email" class="form-control" required>

            <label for="id_user_type">Foydalanuvchi turi</label>
            <select id="id_user_type" name="user_type" class="form-select" required>
                <option value="">Tanlang...</option>
                <option value="sayohatchi">Sayohatchi</option>
                <option value="taxi_egasi">Taxi park egasi</option>
                <option value="gid">Gid (yo‘lboschi)</option>
                <option value="mehmonxona_egasi">Mehmonxona egasi</option>
            </select>

            <label for="id_phone">Telefon raqam</label>
            <input type="text" id="id_phone" name="phone" class="form-control" required>

            <label for="id_country">Davlat</label>
            <input type="text" id="id_country" name="country" class="form-control" required>

            <label for="id_city">Shahar</label>
            <input type="text" id="id_city" name="city" class="form-control" required>

            <label for="id_avatar">Profil rasmi</label>
            <input type="file" id="id_avatar" name="avatar" class="form-control">

            <label for="id_password1">Parol</label>
            <input type="password" id="id_password1" name="password1" class="form-control" required>

            <label for="id_password2">Parolni tasdiqlang</label>
            <input type="password" id="id_password2" name="password2" class="form-control" required>

            <div id="error-message" class="error text-center mb-2"></div>

            <button type="submit" class="btn btn-primary mt-3" id="registerBtn" disabled>
                <i class="fa fa-user-plus me-1"></i> Ro‘yxatdan o‘tish
            </button>

            <div class="text-center mt-3">
                <small>Allaqachon akkauntingiz bormi?
                    <a href="{% url 'login' %}" class="text-primary fw-bold">Kirish</a>
                </small>
            </div>
        </form>
    </div>

    <script>
        const form = document.getElementById('registerForm');
        const registerBtn = document.getElementById('registerBtn');
        const errorMsg = document.getElementById('error-message');
        const inputs = form.querySelectorAll('input[required], select[required]');
        const username = document.getElementById('id_username');
        const pass1 = document.getElementById('id_password1');
        const pass2 = document.getElementById('id_password2');

        function validateForm() {
            let allFilled = true;
            inputs.forEach(input => {
                if (!input.value.trim()) {
                    allFilled = false;
                }
            });

            let error = "";

            if (username.value !== username.value.toLowerCase()) {
                error = "⚠️ Foydalanuvchi nomi faqat kichik harflarda bo‘lishi kerak.";
            } else if (pass1.value && pass2.value && pass1.value !== pass2.value) {
                error = "⚠️ Parollar bir-biriga mos emas.";
            }

            if (error) {
                errorMsg.innerText = error;
                registerBtn.disabled = true;
            } else if (allFilled) {
                errorMsg.innerText = "";
                registerBtn.disabled = false;
            } else {
                registerBtn.disabled = true;
                errorMsg.innerText = "";
            }
        }

        form.addEventListener('input', validateForm);
    </script>
</body>
</html>